name: Update PhD Data and Generate Report

on:
  schedule:
    # Run daily at 06:00 UTC (07:00 CET / 08:00 CEST)
    - cron: '0 6 * * *'
  
  # Allow manual triggering
  workflow_dispatch:
  
  # Run on push to main for testing
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Create data directory
      run: mkdir -p data
      
    - name: Fetch PhD data
      run: |
        python fetch_data.py
        
    - name: Generate HTML report
      run: |
        python generate_html.py
        
    - name: Commit and push if data changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Add changes
        git add data/ docs/
        
        # Check if there are changes
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "chore: Update PhD data and report
          
          Automated update of PhD data from AU CS website
          - Fetched latest PhD dissertation data
          - Generated updated HTML report
          - Data includes $(cat data/phd_data.json | python3 -c "import sys, json; data=json.load(sys.stdin); print(f'{len(data)} PhD entries from {min(p[\"year\"] for p in data if p[\"year\"])}-{max(p[\"year\"] for p in data if p[\"year\"])}')")
          
          🤖 Generated by GitHub Actions"
          
          git push
        fi
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      if: github.ref == 'refs/heads/main'
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      if: github.ref == 'refs/heads/main'
      with:
        path: ./docs
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      if: github.ref == 'refs/heads/main'